### ISSUE TITLE
Summary of Issues

### ISSUE THREAD

**Issue by HugleDong** [Glatzel/cli-memo#11]
## 1-CodeIssue
- [ ] Put modification of `timestamp` in the end. #7 
- [ ] Try to figure out the missdata supplements. #12 
## 2-Suggestion
-  Github should be the ultimate ouput of certain stages, not like the git tools. It is critical to keep your Doc or Code clean and Points, which would also help you check back the documents few days later.
-  Learn more syntax about the style of closing issue.

**Comment by Glatzel** [comment]
You can use some syntax mentioned in this link to close issue. https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by Glatzel** [comment]
|  task   | status |comment  |
|  ----  | ----  |----  |
| task1   | solved | https://github.com/Glatzel/cli-memo/issues/11#issuecomment-2194995264|
| task2   | open | |
